### PR TITLE
Fix non-sale captions & not touch items without sales

### PR DESCRIPTION
**Pull request by galeksandrp**
Ignore non-sale captions
- [x] 15% off
- [x] Only 1 left!
- [x] 6 watching

and similar.

### CODE REVIEW

**Comment by eladnava** [comment]
Hi @galeksandrp,
Thanks so much for submitting this PR!

Can you please explain a little better what it aims to achieve? What is the problem that it solves?

Will non-sale items no longer show up? Will they show up at the bottom of the search results?

**Comment by galeksandrp** [comment]
This PR does not change behavior, items with 0 sales shows after results with sales.

**Comment by eladnava** [comment]
Hi @galeksandrp,
This PR has not been merged yet, so behavior is not supposed to change.

Can you please explain a little better what it aims to achieve? What is the problem that it solves?

Will non-sale items no longer show up? Will they show up at the bottom of the search results?

**Comment by galeksandrp** [comment]
Upd.

**Comment by eladnava** [comment]
Hi @galeksandrp,
This is already the current behavior: 
Items with no sale count or discount **do** show up after results with `X sold` or `X% off`. 

Try this search for example and scroll down:
http://www.ebay.com/sch/i.html?_from=R40&_trksid=p2050601.m570.l1313.TR0.TRC0.H0.Xedison+bulb.TRS0&_nkw=edison+bulb&_sacat=0

So what does this PR do?

**Pull request closed without merging**
